/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class Surreal {
  constructor()
  connect(endpoint: string, opts?: any | undefined | null): Promise<void>
  use(value: any): Promise<void>
  set(key: string, value: any): Promise<void>
  unset(key: string): Promise<void>
  signup(credentials: any): Promise<any>
  signin(credentials: any): Promise<any>
  invalidate(): Promise<void>
  authenticate(token: string): Promise<void>
  query(sql: string, bindings: any): Promise<any>
  select(resource: string): Promise<any>
  create(resource: string, data: any): Promise<any>
}
